apiVersion: v1
kind: Service
metadata:
  name: service-nginx-helm
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: deployment-nginx-helm
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80